sign up api's work complete and navigate to create shop
dassajib/bikree-frontend pull request #1
Opened 2024-07-16 16:07 UTC by dassajib

Sign up work done using react-query, zustand. Please review the code and give me feedback bhai.

2024-07-29 07:06 UTC, salman1204 commented on src/Components/Shops/CreateShop.tsx
> +  return (
use 'useForm' hook to initialise the Form. and add the Datatype there which will help you to validate the dataType of the form. 

`const [form] = useForm<FormSubmitEventInterface>()`

2024-07-29 07:09 UTC, salman1204 commented on src/Components/SignUp/SignUp.tsx
>  const SignUp: React.FC = () => {
React.FC is unnecessary . Currently the new version of react doesn't need this.

2024-07-29 07:14 UTC, salman1204 commented on src/index.css
Don't put the local component's css class in the index.css file

2024-07-29 07:16 UTC, salman1204 commented on src/interface/index.ts
> +export interface SignupData {
make separate file for putting signUp interface. Do put all the interface of the entire application in a single file. Categorise it and make separate file according that.

2024-07-29 07:27 UTC, salman1204 commented
@dassajib UI is not up to the mark. also the signup card gets increase while removing the phone number. The cards are too narrow for the bigger screen. 

> Make sure you are utilising Typescript properly.
> Do study on antd Form as you have to work a lot with Form. 
> Try to use tailwind class As much as possible rather than writing css by yourself.
> Pay Attention to the UI and take care of responsiveness.
> Validate the Data of the form item. 
> Before sending any PR, make sure you have written your best code.But don't try to be perfectionist all the time, it will kill your efficiency. Just be balanced. 

thanks.I appreciate your efforts.

2024-07-29 07:31 UTC, salman1204 commented on src/main.tsx
> +    </QueryClientProvider>
Why you call the <BrowserRouter> twice? I think, you should not wrap the application with BrowserRouter twice. Instead, you should structure it in a way where the QueryClientProvider and BrowserRouter are properly nested

something like below : 
` <QueryClientProvider client={queryClient}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </QueryClientProvider>`

2024-07-29 07:37 UTC, salman1204 commented on .env
> +VITE_BACKEND_URL="http://127.0.0.1:8000/api/v1"
Don't put .env in the git. Add this file in the git ignore.

And create a new file named  .env.example where you just write the variables name of the .env file. not the values of those.

2024-07-29 07:43 UTC, salman1204 commented on src/interface/index.ts
> +export interface SignupData {
Also follow a naming pattern for interface, Ex: SignupDataInterface,SignupResponseInterface

2024-07-30 18:21 UTC, dassajib commented on src/main.tsx
> +    </QueryClientProvider>
bhai i can not understand where the problem is. My current code of main.tsx is matched with your example that you gave.

2024-08-10 06:01 UTC, salman1204 commented on src/Components/Shops/CreateShop.tsx
> +  return (
I don't see any changes.Can you confirm this, you have changed according to my comment?

2024-08-10 06:04 UTC, salman1204 commented on .env
> +VITE_BACKEND_URL="http://127.0.0.1:8000/api/v1"
delete this .env file from this branch. There won't be any file called .env

2024-08-10 06:06 UTC, salman1204 commented on src/Components/Shops/CreateShop.tsx
> +        }}
If possible, handle it with tailwind css.
may be something like below: 
`class="bg-white/30 shadow-[0_8px_32px_rgba(0,0,255,0.33)] p-16 rounded-lg"`

2024-08-10 06:10 UTC, salman1204 requested changes
Add a "Page" folder from where we will add index file for each route.

2024-08-10 15:51 UTC, salman1204 approved these changes

2024-08-19 17:32 UTC, closed without merging